### ISSUE TITLE
 Undefined index: receiverList.receiver(0).primary i Receiver::parseReceivers

### ISSUE THREAD

**Issue by kristofferwiklund** [PaysonAB/module-payson-drupalcommerce#1]
Hi

We have started using your module. But now we get the following errors in our logs:

Notice: Undefined index: receiverList.receiver(0).primary i Receiver::parseReceivers() (row 46 of /path/to/site/sites/all/modules/payson_api/lib/receiver.php).

With the following path:
http://domain/payson_api/ipn/payson_api_pay%7Ccommerce_payment_payson_api_pay

**Comment by PaysonAB** [comment]
Hi,

We have now released a fix to solve this , please reinstall the module to fix the issue.
If you experienceing any further issue regardin this issue please contact us <a href="https://www.payson.se/myaccount/contact/contact">here</a>

Best regards
Payson Integration
